- hosts: all
  become: yes
  vars_files:
    - vars/env.yml

  tasks:
    - name: Ping UBUNTU Image
      ansible.builtin.ping:

    - name: Set Users
      include_tasks: tasks/set_users.yml

    - name: Set Env Variables
      include_tasks: tasks/set_env_vars.yml

    - name: Install APT packages
      include_tasks: tasks/apt_install.yml
    
    - name: Set motd
      include_tasks: tasks/motd.yml

    - name: Install Intel Certs
      include_tasks: tasks/install_cert.yml

    - name: Resize partition
      include_tasks: tasks/resize_part.yml
      
    - name: Install Desktop
      include_tasks: tasks/install_desktop.yml

    - name: Install NTP
      import_role:
        name: /root/.ansible/roles/geerlingguy.ntp
      vars:
        ntp_timezone: Europe/Warsaw
        ntp_manage_config: true
        ntp_servers:
          - "corp.intel.com iburst"

    - name: Install Docker
      include_tasks: tasks/install_docker.yml

    - name: Install Golang
      import_role:
        name: /root/.ansible/roles/geerlingguy.go

    - name: Install VS CODE
      import_role:
        name: /root/.ansible/roles/gantsign.visual-studio-code
    




      
      