- name: populate /etc/environment
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ os_environment }}"

- name: populate /etc/wgetrc
  lineinfile:
    dest: "/etc/wgetrc"
    state: present
    regexp: "^#{{ item.key }} ="
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ wget_proxy }}"